model: "qwen-plus"
base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key: "sk-xxxx"  # Note: Storing secrets directly in YAML is often discouraged for production. See .env method.
max_tokens: 8192
temperature: 0.8
api_type: "Openai"
