model: "qwen-plus"
base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key: "sk-0e349a8dc24443988825b69a56d2b868"  # Note: Storing secrets directly in YAML is often discouraged for production. See .env method.
max_tokens: 16384
temperature: 0.8
api_type: "Openai"

